#!/bin/bash

# Creating the build directory (if it doesn't exist)
mkdir -p build

# Changing to the build directory
cd build

LD_LIBRARY_PATH=$PWD/build/Frontend/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Backend/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/AST/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/Logger/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/Figures/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/SemanticAnalyzer/:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

qmake ../Graph.pro

make
