#!/bin/bash

# Определяем операционную систему
OS=$(uname -s)

# Функция для вывода сообщений об ошибках и выхода
error()
{
  echo "Error: $1" >&2
  exit 1
}

# Определяем команду make
if [[ "$OS" == "Windows_NT" ]]; then
  # Предполагаем, что используется MinGW или MSYS2
  CMAKE_GENERATOR="MinGW Makefiles"
  MAKE="mingw32-make"
  # Проверяем что mingw32-make находится в PATH
  if ! command -v mingw32-make &> /dev/null; then
      echo "mingw32-make не найден в PATH. Пожалуйста, убедитесь, что MinGW установлен и добавлен в PATH."
      exit 1
  fi
else
  CMAKE_GENERATOR="Unix Makefiles"
  MAKE="make"
  #Проверяем что make находится в PATH
  if ! command -v make &> /dev/null; then
      echo "make не найден в PATH. Пожалуйста, убедитесь, что make установлен и добавлен в PATH."
      exit 1
  fi
fi

# Создаем директорию build (если она не существует)
mkdir -p build

# Переходим в директорию build
cd build || error "Не удалось перейти в директорию build"

# Конфигурируем проект с помощью CMake
cmake -G "$CMAKE_GENERATOR" .. || error "Ошибка при конфигурировании CMake"

# Собираем проект
$MAKE || error "Ошибка при сборке проекта"

echo "Сборка успешно завершена!"
