#!/bin/bash

# Функция для вывода сообщений об ошибках и выхода
error()
{
  echo "Error: $1" >&2
  exit 1
}

OS=$(uname -s)

# Определяем расширение исполняемого файла и преобразуем путь, если это Windows
if [[ "$OS" == "MINGW"* || "$OS" == "Windows_NT"* ]]; then
  EXE_EXT=".exe"
else
  EXE_EXT=""
fi

first_arg="$1"
BUILD_DIR="build" # Default to Debug build

if [[  "$first_arg" == "--Debug" ]]; then
    shift
elif [[ "$first_arg" == "--Release" ]]; then
    BUILD_DIR="build_release"
    shift
fi

APP_PATH="./${BUILD_DIR}/bin/Graph${EXE_EXT}"

# Проверяем, что приложение существует
if [ ! -f "$APP_PATH" ]; then
  error "Ошибка: Исполняемый файл '$APP_PATH' не найден. Проверьте, что сборка выполнена в режиме '${BUILD_DIR}'."
fi

$APP_PATH $@

echo "Приложение успешно завершено!"
