#!/bin/bash

if [[ "$OS" == "MINGW"* || "$OS" == "Windows_NT"* ]]; then
    echo "Tests is unsupported on windows" >&2
    exit 1
fi

BUILD_DIR="build"
test_arg="$1"

# Если первым аргументом --Debug или --Relase, то далее смотрим на второй
if [[  "$test_arg" == "--Debug" ]]; then
    test_arg="$2"
elif [[ "$test_arg" == "--Release" ]]; then
    BUILD_DIR="build_release"
    test_arg="$2"
fi

cd $BUILD_DIR

if [[ -z "$test_arg" || "$test_arg" == "--all" ]]; then
    ctest . --output-on-failure
elif [[ "$test_arg" == "--Common" ]]; then
    ctest -R "(ASTTest|LoggerTest|FileManagerTest|SemanticAnalyzerTest|RetranslatorTest|FiguresStorageTest)" . --output-on-failure
elif [[ "$test_arg" == "--Backend" ]]; then
    ctest -R BackendTest --output-on-failure
elif [[ "$test_arg" == "--AST" ]]; then
    ctest -R ASTTest --output-on-failure
elif [[ "$test_arg" == "--Logger" ]]; then
    ctest -R LoggerTest --output-on-failure
elif [[ "$test_arg" == "--FileManager" ]]; then
    ctest -R FileManagerTest --output-on-failure
elif [[ "$test_arg" == "--SA" ]]; then
    ctest -R SemanticAnalyzerTest --output-on-failure
elif [[ "$test_arg" == "--Retranslator" ]]; then
    ctest -R RetranslatorTest --output-on-failure
elif [[ "$test_arg" == "--FiguresStorage" ]]; then
    ctest -R FiguresStorageTest --output-on-failure
else
    echo "Usage: $0 [--all | --Common | --Backend | --AST | --Logger | --FileManager | --SA | --Retranslator | --FiguresStorage]" >&2
    exit 1
fi

echo "Тесты завершены."
