name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  QT_VERSION: 5.15.2

jobs:
  install_packages:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          dir: .
          install-deps: true
          setup-python: false

  build:
    needs: install_packages
    runs-on: ubuntu-latest

    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          dir: .
          install-deps: true
          setup-python: false

      - name: Set up PATH for qmake
        run: |
          echo "Adding Qt bin directory to PATH"
          echo "PATH=$(pwd)/Qt/5.15.2/gcc_64/bin:$PATH" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod +x Build
          ./Build

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          dir: .
          install-deps: true
          setup-python: false
      
      - name: Set up PATH for qmake
        run: |
          echo "Adding Qt bin directory to PATH"
          echo "PATH=$(pwd)/Qt/5.15.2/gcc_64/bin:$PATH" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod +x Build
          ./Build

      - name: Run tests
        run: |
          chmod +x runTest
          ./runTest
 